//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirplaneType
    {
        public AirplaneType()
        {
            this.Airplane = new HashSet<Airplane>();
        }
    
        public int airplane_type { get; set; }
        public Nullable<int> econom_seats_count { get; set; }
        public Nullable<int> business_seats_count { get; set; }
        public Nullable<int> crew_count { get; set; }
        public Nullable<int> carrying { get; set; }
        public string name_ { get; set; }
    
        public virtual ICollection<Airplane> Airplane { get; set; }
        public virtual AirplaneTypeCoefficient AirplaneTypeCoefficient { get; set; }
    }
}
