//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirportEntities : DbContext
    {
        public AirportEntities()
            : base("name=AirportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Airplane> Airplane { get; set; }
        public virtual DbSet<AirplaneType> AirplaneType { get; set; }
        public virtual DbSet<AirplaneTypeCoefficient> AirplaneTypeCoefficient { get; set; }
        public virtual DbSet<Flight> Flight { get; set; }
        public virtual DbSet<Passenger> Passenger { get; set; }
        public virtual DbSet<PermanentCoefficients> PermanentCoefficients { get; set; }
        public virtual DbSet<Seat> Seat { get; set; }
        public virtual DbSet<StatusFlight> StatusFlight { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<Table> Table { get; set; }
    }
}
