//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airplane
    {
        public Airplane()
        {
            this.Flight = new HashSet<Flight>();
        }
    
        public int ID_airplane { get; set; }
        public Nullable<int> airplane_type { get; set; }
    
        public virtual AirplaneType AirplaneType { get; set; }
        public virtual ICollection<Flight> Flight { get; set; }
    }
}
