//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public Flight()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int ID_flight { get; set; }
        public Nullable<int> ID_airplane { get; set; }
        public string city_departure { get; set; }
        public string city_destination { get; set; }
        public string airport_departure { get; set; }
        public string airport_destination { get; set; }
        public string terminal_departure { get; set; }
        public string terminal_destination { get; set; }
        public string gates_departure { get; set; }
        public string gates_destination { get; set; }
        public Nullable<System.TimeSpan> time_flight { get; set; }
        public Nullable<int> miles_count { get; set; }
    
        public virtual Airplane Airplane { get; set; }
        public virtual StatusFlight StatusFlight { get; set; }
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
