//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        public Passenger()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int ID_passport { get; set; }
        public string fio { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string sex { get; set; }
    
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
