//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermanentCoefficients
    {
        public int Id { get; set; }
        public Nullable<double> mileCoefficient { get; set; }
        public Nullable<double> economClassCoefficient { get; set; }
        public Nullable<double> BusinessClassCoefficient { get; set; }
        public Nullable<double> buyDateCoefficient { get; set; }
    }
}
