//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public int ID_seat { get; set; }
        public Nullable<int> status_seat { get; set; }
        public Nullable<int> @class { get; set; }
        public Nullable<int> number_seat { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
