//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airport
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusFlight
    {
        public int ID_flight { get; set; }
        public string status_flight { get; set; }
        public Nullable<System.DateTime> date_departure { get; set; }
        public Nullable<System.TimeSpan> time_departure { get; set; }
        public Nullable<System.DateTime> date_destination { get; set; }
    
        public virtual Flight Flight { get; set; }
    }
}
